name: pokegame
services:
  pokegame_mongo:
    image: mongo
    container_name: PokeGame_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: pokegame
      MONGO_INITDB_ROOT_PASSWORD: kYpKaNJvVUAX3Eg9
    ports:
      - 27032:27017

  pokegame_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: PokeGame_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: AT42S6a5KdL3HxnC
    ports:
      - 1442:1433

  pokegame_postgres:
    image: postgres
    container_name: PokeGame_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: TRs5VEJQZKDzh4ur
    ports:
      - 5442:5432

  pokegame_backend:
    build:
      context: ./backend
      dockerfile: /src/PokeGame/Dockerfile
    image: pokegame_backend
    container_name: PokeGame_backend
    depends_on:
      - pokegame_mongo
      - pokegame_mssql
      - pokegame_postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
      POSTGRESQLCONNSTR_Pokemon: "User ID=postgres;Password=TRs5VEJQZKDzh4ur;Host=pokegame_postgres;Port=5432;Database=Pokemon;"
      SQLCONNSTR_Pokemon: "Server=pokegame_mssql;Database=Pokemon;User Id=SA;Password=AT42S6a5KdL3HxnC;Persist Security Info=False;Encrypt=False;"
    ports:
      - 8092:8080
