CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Event') THEN
        CREATE SCHEMA "Event";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Event') THEN
        CREATE SCHEMA "Event";
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "Event"."Events" (
    "Sid" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "OccurredOn" timestamp with time zone NOT NULL DEFAULT (now()),
    "UserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    "Version" integer NOT NULL DEFAULT 0,
    "EventType" character varying(256) NOT NULL,
    "EventData" jsonb NOT NULL,
    "AggregateType" character varying(256) NOT NULL,
    "AggregateId" uuid NOT NULL,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Sid")
);

CREATE INDEX "IX_Events_AggregateType_AggregateId" ON "Event"."Events" ("AggregateType", "AggregateId");

CREATE UNIQUE INDEX "IX_Events_Id" ON "Event"."Events" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221010215958_Release_0.1.0', '6.0.9');

COMMIT;
