// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeGame.Infrastructure.ReadModel;

#nullable disable

namespace PokeGame.Infrastructure.ReadModel.Migrations
{
    [DbContext(typeof(ReadContext))]
    [Migration("20220930035636_AddedTrainerPokedexCountAndNational")]
    partial class AddedTrainerPokedexCountAndNational
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ReadModel")
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.AbilityEntity", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AbilityId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sid"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Sid");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Abilities", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.EvolutionEntity", b =>
                {
                    b.Property<int>("EvolvingSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("EvolvedSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("HighFriendship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<byte>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Method")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("MoveId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeOfDay")
                        .HasColumnType("integer");

                    b.HasKey("EvolvingSpeciesId", "EvolvedSpeciesId");

                    b.HasIndex("EvolvedSpeciesId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MoveId");

                    b.ToTable("Evolutions", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.InventoryEntity", b =>
                {
                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("TrainerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventory", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.ItemEntity", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ItemId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sid"));

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<double?>("DefaultModifier")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Sid");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Items", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.MoveEntity", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MoveId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sid"));

                    b.Property<byte?>("Accuracy")
                        .HasColumnType("smallint");

                    b.Property<short>("AccuracyStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<short>("EvasionStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte?>("Power")
                        .HasColumnType("smallint");

                    b.Property<byte>("PowerPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("StatisticStages")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte?>("StatusChance")
                        .HasColumnType("smallint");

                    b.Property<int?>("StatusCondition")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("VolatileConditions")
                        .HasColumnType("text");

                    b.HasKey("Sid");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Moves", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokedexEntity", b =>
                {
                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCaught")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrainerId", "SpeciesId");

                    b.HasIndex("HasCaught");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Pokedex", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonEntity", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PokemonId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sid"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int?>("BallId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<int>("CurrentHitPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("CurrentTrainerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EffortValues")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<byte>("Friendship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("IndividualValues")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<byte?>("MetAtLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("MetLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("MetOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OriginalTrainerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("RemainingHatchSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("Statistics")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StatusCondition")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Sid");

                    b.HasIndex("AbilityId");

                    b.HasIndex("BallId");

                    b.HasIndex("CurrentTrainerId");

                    b.HasIndex("Gender");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OriginalTrainerId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("Surname");

                    b.ToTable("Pokemon", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonMoveEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.Property<byte>("Position")
                        .HasColumnType("smallint");

                    b.Property<byte>("RemainingPowerPoints")
                        .HasColumnType("smallint");

                    b.HasKey("PokemonId", "MoveId");

                    b.HasIndex("MoveId");

                    b.HasIndex("PokemonId", "Position")
                        .IsUnique();

                    b.ToTable("PokemonMoves", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonPositionEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<byte>("Box")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("PokemonId");

                    b.HasIndex("TrainerId", "Position", "Box")
                        .IsUnique();

                    b.ToTable("PokemonPositions", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.RegionalSpeciesEntity", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("SpeciesId", "Region");

                    b.HasIndex("Region", "Number")
                        .IsUnique();

                    b.ToTable("RegionalSpecies", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.SpeciesAbilityEntity", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.HasKey("SpeciesId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("SpeciesAbilities", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SpeciesId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sid"));

                    b.Property<int?>("BaseExperienceYield")
                        .HasColumnType("integer");

                    b.Property<byte>("BaseFriendship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("BaseStatistics")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte?>("CatchRate")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EvYield")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("GenderRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("LevelingRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Picture")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("PrimaryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("SecondaryType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Sid");

                    b.HasIndex("Category");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PrimaryType");

                    b.HasIndex("SecondaryType");

                    b.ToTable("Species", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrainerId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sid"));

                    b.Property<byte>("Checksum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NationalPokedex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Picture")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("PlayTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PokedexCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Region")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Sid");

                    b.HasIndex("Gender");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Region");

                    b.HasIndex("UserId");

                    b.HasIndex("Region", "Number", "Name")
                        .IsUnique();

                    b.ToTable("Trainers", "ReadModel");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.EvolutionEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", "EvolvedSpecies")
                        .WithMany("EvolvedFrom")
                        .HasForeignKey("EvolvedSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", "EvolvingSpecies")
                        .WithMany("Evolutions")
                        .HasForeignKey("EvolvingSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.ItemEntity", "Item")
                        .WithMany("Evolutions")
                        .HasForeignKey("ItemId");

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.MoveEntity", "Move")
                        .WithMany("Evolutions")
                        .HasForeignKey("MoveId");

                    b.Navigation("EvolvedSpecies");

                    b.Navigation("EvolvingSpecies");

                    b.Navigation("Item");

                    b.Navigation("Move");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.InventoryEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.ItemEntity", "Item")
                        .WithMany("Inventory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", "Trainer")
                        .WithMany("Inventory")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokedexEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", "Species")
                        .WithMany("Pokedex")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", "Trainer")
                        .WithMany("Pokedex")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.AbilityEntity", "Ability")
                        .WithMany("Pokemon")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.ItemEntity", "Ball")
                        .WithMany()
                        .HasForeignKey("BallId");

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", "CurrentTrainer")
                        .WithMany("Pokemon")
                        .HasForeignKey("CurrentTrainerId");

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.ItemEntity", "HeldItem")
                        .WithMany()
                        .HasForeignKey("HeldItemId");

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", "OriginalTrainer")
                        .WithMany("OriginalPokemon")
                        .HasForeignKey("OriginalTrainerId");

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", "Species")
                        .WithMany("Pokemon")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Ball");

                    b.Navigation("CurrentTrainer");

                    b.Navigation("HeldItem");

                    b.Navigation("OriginalTrainer");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonMoveEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.MoveEntity", "Move")
                        .WithMany("PokemonMoves")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.PokemonEntity", "Pokemon")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonPositionEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.PokemonEntity", "Pokemon")
                        .WithOne("Position")
                        .HasForeignKey("PokeGame.Infrastructure.ReadModel.Entities.PokemonPositionEntity", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", "Trainer")
                        .WithMany("PokemonPositions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.RegionalSpeciesEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", "Species")
                        .WithMany("RegionalSpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.SpeciesAbilityEntity", b =>
                {
                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.AbilityEntity", "Ability")
                        .WithMany("SpeciesAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", "Species")
                        .WithMany("SpeciesAbilities")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.AbilityEntity", b =>
                {
                    b.Navigation("Pokemon");

                    b.Navigation("SpeciesAbilities");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.ItemEntity", b =>
                {
                    b.Navigation("Evolutions");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.MoveEntity", b =>
                {
                    b.Navigation("Evolutions");

                    b.Navigation("PokemonMoves");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.PokemonEntity", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.SpeciesEntity", b =>
                {
                    b.Navigation("Evolutions");

                    b.Navigation("EvolvedFrom");

                    b.Navigation("Pokedex");

                    b.Navigation("Pokemon");

                    b.Navigation("RegionalSpecies");

                    b.Navigation("SpeciesAbilities");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.ReadModel.Entities.TrainerEntity", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("OriginalPokemon");

                    b.Navigation("Pokedex");

                    b.Navigation("Pokemon");

                    b.Navigation("PokemonPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
