name: Build PokeGame Web Application Backend

on:
  push:
    branches:
      - architecture
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - architecture
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    name: Build PokeGame Web Application Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Test Solution
        run: dotnet test --no-build --verbosity normal --filter Category=Unit
